ALTER TABLE bus ADD compagnie_id INT NOT NULL;
     ALTER TABLE bus ADD CONSTRAINT FK_2F566B6952FBE437 FOREIGN KEY (compagnie_id) REFERENCES compagnie (id);
     CREATE INDEX IDX_2F566B6952FBE437 ON bus (compagnie_id);
     ALTER TABLE agence ADD retenu TINYINT(1) NOT NULL;
     ALTER TABLE pack ADD limite DATE DEFAULT NULL;
     ALTER TABLE pack CHANGE taux taux DOUBLE PRECISION DEFAULT NULL;