<?php

namespace App\Repository;

/**
 * ChambreMecqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChambreMecqueRepository extends \Doctrine\ORM\EntityRepository
{
	public function medine($agence, $session)
	{
		// On passe par le QueryBuilder vide de l'EntityManager pour l'exemple
		$query = $this ->createQueryBuilder('a') 
					->Join('a.hotel', 's', 'WITH', 's.lieu = :lieu')
					->setParameter('lieu', 'Medine')
					->addSelect('s')
					->AndWhere('a.session = :session')
					->setParameter('session', $session)
					->AndWhere('a.agence = :agence')
					->setParameter('agence', $agence)
					->getQuery();
		return $query->getResult();
	}
	
	public function mecque($agence, $session)
	{
		// On passe par le QueryBuilder vide de l'EntityManager pour l'exemple
		$query = $this ->createQueryBuilder('a') 
					->Join('a.hotel', 's', 'WITH', 's.lieu = :lieu') 
					->setParameter('lieu', 'Mecque')
					->addSelect('s')
					->AndWhere('a.session = :session')
					->setParameter('session', $session)
					->AndWhere('a.agence = :agence')
					->setParameter('agence', $agence)
					->getQuery();
		return $query->getResult();
	}
	
}
