<?php

namespace App\Repository;

/**
 * CompagnieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompagnieRepository extends \Doctrine\ORM\EntityRepository
{
	public function aerienne($agence)
	{
		// On passe par le QueryBuilder vide de l'EntityManager pour l'exemple
		$query = $this ->createQueryBuilder('a')
					->Where('a.agence = :agence')
					->setParameter('agence', $agence)
					->andWhere('a.type = :type')
					->setParameter('type', 'Aerienne');
					return $query;
	}
	public function automobile($agence)
	{
		// On passe par le QueryBuilder vide de l'EntityManager pour l'exemple
		$query = $this ->createQueryBuilder('a')
					->Where('a.agence = :agence')
					->setParameter('agence', $agence)
					->andWhere('a.type = :type')
					->setParameter('type', 'Automobile');
					return $query;
	}
	
}
