<?php

namespace App\Repository;

/**
 * CourtierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourtierRepository extends \Doctrine\ORM\EntityRepository
{
}
