<?php

namespace App\Repository;

/**
 * CourtierPelerinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourtierPelerinRepository extends \Doctrine\ORM\EntityRepository
{
	
}
