<?php

namespace App\Repository;

/**
 * DebitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DebitRepository extends \Doctrine\ORM\EntityRepository
{
	public function brouyard($session)
	{
		$query = $this->createQueryBuilder('a')
					->Where('a.date = :genre')
					->setParameter('genre', date('Y-m-d'))
					->andWhere('a.session = :session')
					->setParameter('session', $session)
					->getQuery();
		return $query->getResult();
	}
	public function daybrouyard($date, $session)
	{
		$query = $this->createQueryBuilder('a')
					->Where('a.date = :genre')
					->setParameter('genre', $date)
					->andWhere('a.session = :session')
					->setParameter('session', $session)
					->getQuery();
		return $query->getResult();
	}

	public function plage($date, $date1, $session)
	{
		$query = $this->createQueryBuilder('a')
					->andWhere('a.date BETWEEN :debut AND :fin')
					->setParameter('debut', $date)
					->setParameter('fin', $date1)
					->andWhere('a.session = :session')
					->setParameter('session', $session)
					->getQuery();
		return $query->getResult();
	}

	public function ouverture($session)
	{
		$query = $this->createQueryBuilder('a')
					->Where('a.date < :genre')
					->setParameter('genre', date('Y-m-d'))
					->andWhere('a.session = :session')
					->setParameter('session', $session)
					->getQuery();
		return $query->getResult();
	}

	public function ouvertureplace($datedebut, $session)
	{
		$query = $this->createQueryBuilder('a')
					->Where('a.date < :genre')
					->setParameter('genre', $datedebut)
					->andWhere('a.session = :session')
					->setParameter('session', $session)
					->getQuery();
		return $query->getResult();
	}
}
