<?php

namespace App\Repository;

/**
 * GainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GainRepository extends \Doctrine\ORM\EntityRepository
{
}
