<?php

namespace App\Repository;

/**
 * GroupementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupementRepository extends \Doctrine\ORM\EntityRepository
{
}
