<?php

namespace App\Repository;

/**
 * HotelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HotelRepository extends \Doctrine\ORM\EntityRepository
{
	public function medine($session)
	{
		// On passe par le QueryBuilder vide de l'EntityManager pour l'exemple
		$query = $this ->createQueryBuilder('a') 
					->Join('a.id', 's', 'WITH', 's.hotel = a.id')
					->addSelect('s')
					->where('a.lieu = :lieu')
					->setParameter('lieu', 'Medine')
					->AndWhere('s.session = :session')
					->setParameter('session', $session)
					->groupby('s.hotel')
					->getQuery();
		return $query->getResult();
	}
	public function hotel($agence)
	{
		// On passe par le QueryBuilder vide de l'EntityManager pour l'exemple
		$query = $this ->createQueryBuilder('a') 
						->Where('a.lieu = :genre')
						->setParameter('genre', 'Medine')
						->AndWhere('a.agence = :agence')
						->setParameter('agence', $agence);
					return $query;
	}
	public function hotelmecque($agence)
	{
		// On passe par le QueryBuilder vide de l'EntityManager pour l'exemple
		$query = $this ->createQueryBuilder('a') 
						->Where('a.lieu = :genre')
						->setParameter('genre', 'Mecque')
						->AndWhere('a.agence = :agence')
						->setParameter('agence', $agence);
					return $query;
	}
}
