<?php

namespace App\Repository;

/**
 * OldPelerinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OldPelerinRepository extends \Doctrine\ORM\EntityRepository
{
}
