<?php

namespace App\Repository;

/**
 * OrganRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganRepository extends \Doctrine\ORM\EntityRepository
{
}
