<?php

namespace App\Repository;

/**
 * PelerinCourtierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PelerinCourtierRepository extends \Doctrine\ORM\EntityRepository
{
	public function select($session)
	{// selection payement courtier
		$query = $this->createQueryBuilder('a')
					->Where('a.session = :session')
					->setParameter('session', $session)
					->AndWhere('a.payer = :payer')
					->setParameter('payer', false)
					->groupby('a.courtier')
					->getQuery();
		return $query->getResult();
	}
	
	public function state($session)
	{// etat payement courtier
		$query = $this->createQueryBuilder('a')
					->Where('a.session = :session')
					->setParameter('session', $session)
					->groupby('a.courtier')
					->getQuery();
		return $query->getResult();
	}
}
