<?php

namespace App\Repository;

/**
 * PelerinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PelerinWatingRepository extends \Doctrine\ORM\EntityRepository
{
	
}
