<?php

namespace App\Repository;

/**
 * SessionImamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionImamRepository extends \Doctrine\ORM\EntityRepository
{
	
}
