<?php

namespace App\Repository;

/**
 * SessionOrganisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionOrganisateurRepository extends \Doctrine\ORM\EntityRepository
{
	
}
