<?php

namespace App\Repository;

/**
 * VersementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VersementRepository extends \Doctrine\ORM\EntityRepository
{
	public function delVersement($session, array $pel)
	{	
		$query = $this->createQueryBuilder('a');
				$query->remove('MecqueBundle:Credit','a')
					->where($query->expr()->in('a.id', $pel))
					->AndWhere('a.session = :session')
					->setParameter('session', $session);
		return $query->getQuery()->execute();
	}
}
