<?php

namespace App\Repository;

/**
 * VersementAgenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VersementAgenceRepository extends \Doctrine\ORM\EntityRepository
{
}
