<?php

namespace App\Repository;

/**
 * VersementBanqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VersementBanqueRepository extends \Doctrine\ORM\EntityRepository
{
}
