<?php

namespace App\Repository;

/**
 * VisaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisaRepository extends \Doctrine\ORM\EntityRepository
{
}
